name: build

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ">=1.21.0"

    - name: Build
      run: go build -o a

    - name: Test
      run: go test -timeout 1800s -v -race -coverprofile=coverage.txt -covermode=atomic -tags slow_test

    - name: Upload coverage
      uses: codecov/codecov-action@v3
