name: Build and tests

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build_and_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ">=1.21.0"

    - name: Build
      run: go build -o a

    - name: Test
      shell: bash
      run: go test -timeout 1800s -v -race -coverprofile=coverage.txt -covermode=atomic -tags slow_test

    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@29386c70ef20e286228c72b668a06fd0e8399192
      uses: codecov/codecov-action@v1.5.2
